server:
  port: 7776
spring:
  application:
    name: dm-eureka-server-zx
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7776/eureka/